apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"shortener","namespace":"webservice"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"shortener"}},"template":{"metadata":{"labels":{"app":"shortener"}},"spec":{"containers":[{"image":"your-registry/shortener:latest","name":"shortener","ports":[{"containerPort":8080}],"volumeMounts":[{"mountPath":"/data","name":"db-volume"}]}],"volumes":[{"name":"db-volume","persistentVolumeClaim":{"claimName":"shortener-pvc"}}]}}}}
  creationTimestamp: "2026-03-06T02:06:32Z"
  generation: 8
  name: shortener
  namespace: webservice
  resourceVersion: "972026"
  uid: 7f7cce91-f25f-4850-9435-d045c4af9ea4
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: shortener
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-03-06T03:38:55+01:00"
      creationTimestamp: null
      labels:
        app: shortener
    spec:
      containers:
      - env:
        - name: AUTH_BASE_URL
          value: http://auth:5001
        image: nichb/shortener:latest
        imagePullPolicy: Always
        name: shortener
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2026-03-06T02:42:29Z"
    lastUpdateTime: "2026-03-06T02:42:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-03-06T02:26:14Z"
    lastUpdateTime: "2026-03-11T17:29:15Z"
    message: ReplicaSet "shortener-d8889d4f4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 8
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3